### ISSUE TITLE
Tippfehler in "Teaser" der Seite auf anderen Web-Seiten

### ISSUE THREAD

**Issue by SmartBulb67** [falschparkenffm/homepage#15]
Hallo zusammen,
eben habe ich Eure Seite in einem Kommentar auf der Web-Seite "nebenan.de" verlinkt und dabei wird automatisch eine Kurz-Info oder ein Teaser angezeigt.
Genau dort befindet sich ein Tippfehler und es steht dort "Falscharker behindern..." anstatt "Falschparker behindern...".
Bitte korrigieren.

Schönen Tag noch

**Comment by falschparkenffm** [comment]
Hallo und vielen Dank für den wichtigen Hinweis, ist korrigiert! Eigentlich erstaunlich, dass das erst jetzt aufgefallen ist...
