### ISSUE TITLE
weg.li funktioniert in Frankfurt nicht mehr

### ISSUE THREAD

**Issue by Daniel-at-git** [falschparkenffm/homepage#18]
Anzeigen, die über weg.li gemeldet werden, werden an die Mailadresse owi.datenerfassung.amt32@stadt-frankfurt.de gesendet. Diese Mailadresse wurde vor einigen Wochen deaktiviert und es gibt auch keine alternative Mail-Adresse.

Die Stadt Frankfurt hat jetzt ihr eigenes Portal und hat daher die Mailadressen deaktiviert. In weg.li sieht man dies auch unter "Antwort"

Soll auf der Homepage "weg.li" durch das [neue Portal](https://portal-civ.ekom21.de/civ.public/start.html?oe=00.00.FF.OrdA&mode=cc&cc_key=AnzeigeOwi) ersetzt werden? Komfortable ist es nicht :-(
Oder liebe auf die [Homepage](https://frankfurt.de/service-und-rathaus/verwaltung/aemter-und-institutionen/ordnungsamt/bussgeldstelle/verkehrsordnungswidrigkeiten-im-ruhenden-verkehr) verweisen, in der auch eine PDF zu finden ist, die man dann faxen kann?

**Comment by Daniel-at-git** [comment]
Angepasst werden müsste es ab
[https://github.com/falschparkenffm/homepage/blob/master/content/homepage/privatanzeige.md?plain=1#L19](https://github.com/falschparkenffm/homepage/blob/master/content/homepage/privatanzeige.md?plain=1#L19)

**Comment by falschparkenffm** [comment]
Danke für den Hinweis, ist jetzt (endlich) auch eingebaut.
