### ISSUE TITLE
Abgrenzung Stadtpolizei - städtische Verkehrspolizei

### ISSUE THREAD

**Issue by FrankfurterRadler** [falschparkenffm/homepage#2]
Die städtische Verkehrspolizei ist auch an den Wochenenden (Sonntag) nicht im Dienst. Ruft man sie am Samstag an und verlangt ihre Dienste, bekommt man in der Regel die Auskunft, dass nur ein 2-Mann-Trupp im Innenstadtbereich im Einsatz ist

Sicher, dass die Stadtpolizei wenig bis nichts mit dem Verkehr zu tun haben? Siehe https://www.frankfurt.de/sixcms/detao%C3%B6-php/detail.php?id=2943&_ffmpar[_id_inhalt]=6734657
"Straßenverkehrsrecht [...] Beseitigung verkehrswidriger Zustände zur akuten Gefahrenabwehr[...]".

**Comment by falschparkenffm** [comment]
Danke, der Absatz wurde vorübergehend etwas überarbeitet. Das wäre eine gute Frage für die Stadt Frankfurt.

**Comment by falschparkenffm** [comment]
Wurde mit 14399f899da3f27569b3975425fa550eb67eeb7a konkretisiert.
