### ISSUE TITLE
Impressum / Unterschriftspflicht / Tipps

### ISSUE THREAD

**Issue by DonQuijote0815** [falschparkenffm/homepage#6]
Liebe Leute,
ein paar Dinge zu Eurer Webseite:
- Frage: gibt es auch für ".info"-Domains eine Impressumspflicht? Wenn ja, könnte das ausgenutzt werden, da kein Impressum existiert.
- der Aufruf zur Anzeige ist prima, nur gibt es dabei ein paar Dinge zu bedenken: 
  1. in der Anzeige steht euer Name, d.h. ihr seid nicht anonym.
  2. soweit ich weiß, werden Anzeigen ohne Unterschrift nicht akzeptiert.
  3. hat die Stadt Frankfurt ein Formular, das zur Anzeige benutzt werden soll (muss?). Link: https://frankfurt.de/sixcms/media.php/1335/32IN15_Verkehrsowi_Anzeige_mit_Merkblatt_Stand_2019-01-11.pdf
  4. Die Wegeheld-App erfasst nicht alle Möglichkeiten, so ist z.B. der "Verkehrsberuhigte Bereich"    
      (Zeichen 325 StVO) nicht erfasst.
- wenn man etwas ändern will, muss man irgendwann auch mal Leute anzeigen, aus meiner Erfahrung
   heraus, kann ich sagen, dass hier und da mit Konsequenzen zu rechnen ist, sprich: da man dem
   Autofahrer damit auf den Schwanz tritt, gibt es Zeitgenossen die meinen Rache üben zu müssen
   und das auch tun.

Und zum Abschluss noch eine Frage: wie kann eine Webseite, die auf GitHub verweist, so 
grottenschlecht gecodet bzw. gehostet sein?
Weiterhin gutes Gelingen!

**Comment by falschparkenffm** [comment]
Hallo,

> Frage: gibt es auch für ".info"-Domains eine Impressumspflicht? Wenn ja, könnte das ausgenutzt werden, da kein Impressum existiert.

Sehen wir aktuell als nicht notwendig an.

> in der Anzeige steht euer Name, d.h. ihr seid nicht anonym.

Das ist korrekt, ja. Wir werden noch einen Hinweis dazu einbauen, da man seine Daten als Zeuge angibt sollte das aber auch selbstverständlich sein. Die persönlichen Daten können im Rahmen der Akteneinsicht gesichtet werden.

> soweit ich weiß, werden Anzeigen ohne Unterschrift nicht akzeptiert.

Das stimmt nicht, digitale Anzeigen per E-Mail ohne Nutzung der Vorlage sind genauso zulässig (siehe Quellenangaben auf der entsprechenden Seite)

> hat die Stadt Frankfurt ein Formular, das zur Anzeige benutzt werden soll (muss?). Link: https://frankfurt.de/sixcms/media.php/1335/32IN15_Verkehrsowi_Anzeige_mit_Merkblatt_Stand_2019-01-11.pdf

Ja, das Formular kann genutzt werden, muss aber nicht. Solange alle Daten vollständig sind ist eine E-Mail nur mit Text (und Beweisfoto) zulässig.

> Die Wegeheld-App erfasst nicht alle Möglichkeiten, so ist z.B. der "Verkehrsberuhigte Bereich" (Zeichen 325 StVO) nicht erfasst.

Da müsstest du dich an die Entwickler der App wenden, wir haben sie nur als alternative Möglichkeit zur Anzeigenerstattung mit aufgenommen.

> Und zum Abschluss noch eine Frage: wie kann eine Webseite, die auf GitHub verweist, so
grottenschlecht gecodet bzw. gehostet sein?

Wenn du es als "grottenschlecht" ansiehst kannst du dich gerne einbringen und per Pull Request Verbesserungen einreichen. Außerdem wäre sachliche Kritik wünschenswert.
